PAN_ParentsBank_Final/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PAN_ParentsBank_Final.Models;

namespace PAN_ParentsBank_Final.Controllers
{
    [Authorize]
    public class AccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Accounts
        public ActionResult Index()
        {
            string currentlyLoggedInUsername = User.Identity.Name;

            var accountsOwner = db.Accounts
                .Where(x => x.Owner == currentlyLoggedInUsername).ToList();
            var accountRecipient = db.Accounts
              .Where(x => x.Recipient == currentlyLoggedInUsername).ToList();
            if (accountRecipient != null && accountRecipient.Count > 0)
            {
                Account recipientAccount = accountRecipient.First();
                return RedirectToAction("Details", new { Id = recipientAccount.Id });
            }
            if (accountsOwner == null || !(accountsOwner.Count > 0))
            {
                return RedirectToAction("Create");
            }
            else
            {
                return View(accountsOwner);
            }
        }

        // GET: Accounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // GET: Accounts/Create
        public ActionResult Create()
        {
            if (checkListForValue(getListOfRecipients(), User.Identity.Name)){
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Owner,Recipient,Name,InterestRate")] Account account)
        {
            if (checkListForValue(getListOfRecipients(), account.Recipient))
            {
                ModelState.AddModelError("Recipient", "Recipient already has an account");
            }

            if (checkListForValue(getListOfOwners(), account.Recipient))
            {
                ModelState.AddModelError("Recipient", "Recipient is present as owner in the system");
            }

            if (ModelState.IsValid)
            {
                account.OpenDate = DateTime.Now;
                db.Accounts.Add(account);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(account);
        }

        // GET: Accounts/Edit/5
        public ActionResult Edit(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            if (!account.IsOwner(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }


            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Owner,Recipient,Name,InterestRate")] Account account)
        {
            if (ModelState.IsValid)
            {
                account.OpenDate = DateTime.Now;
                db.Entry(account).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(account);
        }

        // GET: Accounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            if (!account.IsOwner(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(account);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Account account = db.Accounts.Find(id);
            db.Accounts.Remove(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        private List<string> getListOfOwners()
        {
            var accountsOwner = db.Accounts.Select(x => x.Owner);
            return accountsOwner.ToList();
        }

        private List<string> getListOfRecipients()
        {
            var accountsRecipient = db.Accounts.Select(x => x.Recipient);
            return accountsRecipient.ToList();
        }


        private bool checkListForValue(List<string> list, string value)
        {
            if (list != null && list.Count > 0 && !string.IsNullOrWhiteSpace(value))
            {
                return list.Contains(value);
            }
            else
            {
                return false;
            }
        }

    }
}

PAN_ParentsBank_Final/Controllers/TransactionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PAN_ParentsBank_Final.Models;

namespace PAN_ParentsBank_Final.Controllers
{
    [Authorize]
    public class TransactionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Transactions
        public ActionResult Index()
        {
            string currentlyLoggedInUser = User.Identity.Name;
            var transactions = db.Transactions
                .Include(t => t.Account)
                 .Where(x => x.Account.Owner == currentlyLoggedInUser || x.Account.Recipient == currentlyLoggedInUser);
            return View(transactions.ToList());
        }

        // GET: Transactions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            if (!transaction.Account.IsOwnerOrRecipient(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(transaction);
        }

        // GET: Transactions/Create
        public ActionResult Create()
        {

            string currentlyLoggedInUsername = User.Identity.Name;
            if (checkListForValue(getListOfRecipients(), User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            var accounts = db.Accounts
                .Where(x => x.Owner == currentlyLoggedInUsername
                || x.Recipient == currentlyLoggedInUsername).ToList();
            ViewBag.AccountId = new SelectList(accounts, "Id", "Recipient");
            return View();
        }

        // POST: Transactions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AccountId,TransactionDate,Amount,Note,TypeOfTransaction")] Transaction transaction)
        {
            var account = db.Accounts.Find(transaction.AccountId);
            if (transaction.TypeOfTransaction == "Debit" && transaction.Amount > account.getAccountBalance())
            {
                ModelState.AddModelError("Amount", "Insufficient Balance");
            }

            if (ModelState.IsValid)
            {
                db.Transactions.Add(transaction);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccountId = new SelectList(db.Accounts, "Id", "Owner", transaction.AccountId);
            return View(transaction);            
        }

        // GET: Transactions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            if (!transaction.Account.IsOwner(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            string currentlyLoggedInUsername = User.Identity.Name;
            var accounts = db.Accounts
                .Where(x => x.Owner == currentlyLoggedInUsername
                || x.Recipient == currentlyLoggedInUsername).ToList();
            ViewBag.AccountId = new SelectList(accounts, "Id", "Recipient");
            return View(transaction);
        }

        // POST: Transactions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AccountId,TransactionDate,Amount,Note,TypeOfTransaction")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(transaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AccountId = new SelectList(db.Accounts, "Id", "Owner", transaction.AccountId);
            return View(transaction);
        }

        // GET: Transactions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Transaction transaction = db.Transactions.Find(id);
            if (transaction == null)
            {
                return HttpNotFound();
            }
            if (!transaction.Account.IsOwner(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(transaction);
        }

        // POST: Transactions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Transaction transaction = db.Transactions.Find(id);
            db.Transactions.Remove(transaction);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private List<string> getListOfRecipients()
        {
            var accountsRecipient = db.Accounts.Select(x => x.Recipient);
            return accountsRecipient.ToList();
        }


        private bool checkListForValue(List<string> list, string value)
        {
            if (list != null && list.Count > 0 && !string.IsNullOrWhiteSpace(value))
            {
                return list.Contains(value);
            }
            else
            {
                return false;
            }
        }
    }
}

PAN_ParentsBank_Final/Views/Transactions/Create.cshtml
@model PAN_ParentsBank_Final.Models.Transaction


<h2>CREATE TRANSACTION</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class="control-label col-md-2">RECIPIENT EMAIL ID</label>
            <div class="col-md-10">
                @Html.DropDownList("AccountId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <h5><strong>TRANSACTION DATE</strong></h5>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionDate, new { htmlAttributes = new { @class = "form-control", @style="height:40px" } })
                @Html.ValidationMessageFor(model => model.TransactionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <h5><strong>TRANSACTION AMOUNT</strong></h5>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @style = "height:40px" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <h5><strong>NOTE</strong></h5>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control", @style = "height:40px" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>            
        </div>        

        <div class="form-group">
            <div class="control-label col-md-2">
                <h5><strong>TRANSACTION TYPE</strong></h5>
            </div>
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.TypeOfTransaction, "Debit", new { htmlAttributes = new { @class = "form-control", @checked="true" } }) Debit
                @Html.RadioButtonFor(model => model.TypeOfTransaction, "Credit", new { htmlAttributes = new { @class = "form-control"} }) Credit
                @Html.ValidationMessageFor(model => model.TypeOfTransaction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="CREATE TRANSACTION" class="btn btn-danger" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Index", "Transactions")';return false;">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> BACK TO LIST
    </button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PAN_ParentsBank_Final/Views/Transactions/Delete.cshtml
@model PAN_ParentsBank_Final.Models.Transaction

<h2>DELETE TRANSACTION</h2>

<br />

<div>
    <h4>TRANSACTION SUMMARY</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            PARENT EMAIL ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account.Owner)
        </dd>

        <dt>
            TRANSACTION DATE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionDate)
        </dd>

        <dt>
            AMOUNT DATE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <dt>
            NOTES
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <dt>
            TRANSACTION TYPE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfTransaction)
        </dd>

    </dl>

    <br />

    <h4>Are you sure you want to delete this transaction?</h4>

    <br />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @*<div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>*@

        <div class="form-actions no-color">
            <input type="submit" value="YES, DELETE" class="btn btn-danger" /> |
            <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index", "Transactions")';return false;">
                <span class="glyphicon glyphicon-circle-arrow-left"></span> NO, BACK TO LIST
            </button>
        </div>

    }
</div>

PAN_ParentsBank_Final/Views/Transactions/Details.cshtml
@model PAN_ParentsBank_Final.Models.Transaction


<h2>TRANSACTION DETAILS</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            RECIPIENT EMAIL ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account.Recipient)
        </dd>

        <br />

        <dt>
            TRANSACTION DATE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TransactionDate)
        </dd>

        <br />

        <dt>
            TRANSACTION AMOUNT
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Amount)
        </dd>

        <br />

        <dt>
            NOTE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Note)
        </dd>

        <br />

        <dt>
            TRANSACION TYPE
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TypeOfTransaction)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("EDIT TRANSACTION ITEMS", "Edit", new { id = Model.Id, @style = "font-size:20pt" })

    <br />
    <br />

    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index", "TRANSACTIONS")';return false;">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> BACK TO LIST
    </button>
</p>

PAN_ParentsBank_Final/Views/Transactions/Edit.cshtml
@model PAN_ParentsBank_Final.Models.Transaction

<h2>EDIT TRANSACTIONS</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2">RECIPIENT EMAIL ID</label>
            <div class="col-md-10">
                @Html.DropDownList("AccountId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">TRANSACTION DATE</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TransactionDate, new { htmlAttributes = new { @class = "form-control", @style = "height:40px"} })
                @Html.ValidationMessageFor(model => model.TransactionDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">TRANSACTION AMOUNT</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Amount, new { htmlAttributes = new { @class = "form-control", @style = "height:40px" } })
                @Html.ValidationMessageFor(model => model.Amount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">TRANSACTION NOTE</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Note, new { htmlAttributes = new { @class = "form-control", @style = "height:40px" } })
                @Html.ValidationMessageFor(model => model.Note, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">TRANSCTION TYPE</label>
            <div class="col-md-10">
                @Html.RadioButtonFor(model => model.TypeOfTransaction, "Debit", new { htmlAttributes = new { @class = "form-control"} }) Debit
                @Html.RadioButtonFor(model => model.TypeOfTransaction, "Credit", new { htmlAttributes = new { @class = "form-control" } }) Credit
                @Html.ValidationMessageFor(model => model.TypeOfTransaction, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SAVE" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Index", "Transactions")';return false;">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> BACK TO LIST
    </button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PAN_ParentsBank_Final/Views/Transactions/Index.cshtml
@model IEnumerable<PAN_ParentsBank_Final.Models.Transaction>

<h2>TRANSACTION SUMMARY</h2>

<br />

<button type="button" class="btn btn-primary active" 
        onclick="location.href='@Url.Action("create", "Transactions")';
        return false;">ADD NEW TRANSACTION</button>
<br />
<br />
<br />

<table class="table table-bordered">
    <tr>
        <th>
            RECIPIENT EMAIL ID
        </th>
        <th>
            TRANSACTION DATE
        </th>
        <th>
            TRANSACTION AMOUNT
        </th>
        <th>
            NOTE
        </th>
        <th>
            TRANSACTION TYPE
        </th>
        <th>CRUD FUNCTIONALITY </th>
        <th>JUMP TO ACCOUNT DETAILS</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Account.Recipient)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransactionDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Amount)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Note)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TypeOfTransaction)
        </td>
        <td>
            @Html.ActionLink("EDIT TRANS", "Edit", new { id=item.Id }) |
            @Html.ActionLink("TRANS DETAILS", "Details", new { id=item.Id }) |
            @Html.ActionLink("DELETE TRANS", "Delete", new { id=item.Id })
        </td>
        <td>
            <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Details", "Accounts",new { id = item.Account.Id })';return false;">
                <span class="glyphicon glyphicon-circle-arrow-left"></span> GO!
            </button>
            @*@Html.ActionLink("GO!", "Details","Accounts", new { id = item.Account.Id},null)*@
        </td>
    </tr>
}

</table>