PAN_ParentsBank_Final/Controllers/helpController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PAN_ParentsBank_Final.Controllers
{
    public class helpController : Controller
    {
        // GET: help
        [ActionName("financial-resources")]
        public ActionResult Index()
        {
            return View();
        }
    }
}

PAN_ParentsBank_Final/Views/Shared/_Layout.cshtml
@using MvcSiteMapProvider.Web.Html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PARENTS BANK</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-left">
                    <li>@Html.ActionLink("HOME", "Index", "Home")</li>
                    <li>@Html.ActionLink("FINANCIAL RESOURCES", "financial-resources", "help")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right"
                    <li>@Html.Partial("_LoginPartial")</li>
                </ul>                
            </div>
        </div>
    </div>
    <div class="container body-content">
        <div>
            <p style="font-family:'Lucida Sans', 'Lucida Sans Regular', 'Lucida Grande', 'Lucida Sans Unicode', Geneva, Verdana, sans-serif;font-size:15px">You are here:
            @Html.MvcSiteMap().SiteMapPath()
                </p>    
        </div>
        @RenderBody()
        <hr />
          </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>