PAN_ParentsBank_Final/Models/WishlistItem.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace PAN_ParentsBank_Final.Models
{
    public class WishListItem
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        //[Display(Name ="Recipient Account")]
        public virtual int AccountId { get; set; }
        public virtual Account Account { get; set; }
        [Display(Name ="Date Added")]
        [DataType(DataType.Date)]
        public DateTime DateAdded { get; set; }
        [Required]
        [DataType(DataType.Currency)]
        public decimal Cost { get; set; }
        [Required]
        public string Description { get; set; }
        [Url]
        public string Link { get; set; }
        public bool Purchased { get; set; }
    }
}

PAN_ParentsBank_Final/Controllers/AccountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PAN_ParentsBank_Final.Models;

namespace PAN_ParentsBank_Final.Controllers
{
    [Authorize]
    public class AccountsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Accounts
        public ActionResult Index()
        {
            string currentlyLoggedInUsername = User.Identity.Name;

            var accountsOwner = db.Accounts
                .Where(x => x.Owner == currentlyLoggedInUsername).ToList();
            var accountRecipient = db.Accounts
              .Where(x => x.Recipient == currentlyLoggedInUsername).ToList();
            if (accountRecipient != null && accountRecipient.Count > 0)
            {
                Account recipientAccount = accountRecipient.First();
                return RedirectToAction("Details", new { Id = recipientAccount.Id });
            }
            if (accountsOwner == null || !(accountsOwner.Count > 0))
            {
                return RedirectToAction("Create");
            }
            else
            {
                return View(accountsOwner);
            }
        }

        // GET: Accounts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            return View(account);
        }

        // GET: Accounts/Create
        public ActionResult Create()
        {
            if (checkListForValue(getListOfRecipients(), User.Identity.Name)){
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View();
        }

        // POST: Accounts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Owner,Recipient,Name,InterestRate")] Account account)
        {
            if (checkListForValue(getListOfRecipients(), account.Recipient))
            {
                ModelState.AddModelError("Recipient", "Recipient already has an account");
            }

            if (checkListForValue(getListOfOwners(), account.Recipient))
            {
                ModelState.AddModelError("Recipient", "Recipient is present as owner in the system");
            }

            if (ModelState.IsValid)
            {
                account.OpenDate = DateTime.Now;
                db.Accounts.Add(account);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(account);
        }

        // GET: Accounts/Edit/5
        public ActionResult Edit(int? id)
        {
            
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            if (!account.IsOwner(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }


            return View(account);
        }

        // POST: Accounts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Owner,Recipient,Name,InterestRate")] Account account)
        {
            if (ModelState.IsValid)
            {
                account.OpenDate = DateTime.Now;
                db.Entry(account).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(account);
        }

        // GET: Accounts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Account account = db.Accounts.Find(id);
            if (account == null)
            {
                return HttpNotFound();
            }
            if (!account.IsOwner(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden);
            }
            return View(account);
        }

        // POST: Accounts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Account account = db.Accounts.Find(id);
            db.Accounts.Remove(account);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        private List<string> getListOfOwners()
        {
            var accountsOwner = db.Accounts.Select(x => x.Owner);
            return accountsOwner.ToList();
        }

        private List<string> getListOfRecipients()
        {
            var accountsRecipient = db.Accounts.Select(x => x.Recipient);
            return accountsRecipient.ToList();
        }


        private bool checkListForValue(List<string> list, string value)
        {
            if (list != null && list.Count > 0 && !string.IsNullOrWhiteSpace(value))
            {
                return list.Contains(value);
            }
            else
            {
                return false;
            }
        }

    }
}

PAN_ParentsBank_Final/Controllers/WishListItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PAN_ParentsBank_Final.Models;
using System.Text.RegularExpressions;

namespace PAN_ParentsBank_Final.Controllers
{
    [Authorize]
    public class WishListItemsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: WishListItems
        public ActionResult Index()
        {

            string currentlyLoggedInUser = User.Identity.Name;
            var wishListItems = db.WishListItems
                .Include(w => w.Account)
                .Where(x => x.Account.Owner == currentlyLoggedInUser || x.Account.Recipient == currentlyLoggedInUser);
            return View(wishListItems.ToList());
        }

        // GET: WishListItems/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishListItem wishListItem = db.WishListItems.Find(id);
            if (wishListItem == null)
            {
                return HttpNotFound();
            }
            if (!wishListItem.Account.IsOwnerOrRecipient(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(wishListItem);
        }

        // GET: WishListItems/Create
        public ActionResult Create()
        {
            string currentlyLoggedInUsername = User.Identity.Name;
            var accounts = db.Accounts
                .Where(x => x.Owner == currentlyLoggedInUsername
                || x.Recipient == currentlyLoggedInUsername).ToList();
            ViewBag.AccountId = new SelectList(accounts, "Id", "Recipient");
            return View();
        }

        // POST: WishListItems/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,AccountId,DateAdded,Cost,Description,Link,Purchased")] WishListItem wishListItem)
        {
            wishListItem.DateAdded = DateTime.Now;
            if (ModelState.IsValid)
            {
                db.WishListItems.Add(wishListItem);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AccountId = new SelectList(db.Accounts, "Id", "Owner", wishListItem.AccountId);
            return View(wishListItem);
        }

        // GET: WishListItems/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishListItem wishListItem = db.WishListItems.Find(id);
            if (wishListItem == null)
            {
                return HttpNotFound();
            }
            if (!wishListItem.Account.IsOwnerOrRecipient(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            string currentlyLoggedInUsername = User.Identity.Name;
            var accounts = db.Accounts
                .Where(x => x.Owner == currentlyLoggedInUsername
                || x.Recipient == currentlyLoggedInUsername).ToList();
            ViewBag.AccountId = new SelectList(accounts, "Id", "Recipient");
            return View(wishListItem);
        }

        // POST: WishListItems/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,AccountId,DateAdded,Cost,Description,Link,Purchased")] WishListItem wishListItem)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wishListItem).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AccountId = new SelectList(db.Accounts, "Id", "Owner", wishListItem.AccountId);
            return View(wishListItem);
        }

        // GET: WishListItems/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WishListItem wishListItem = db.WishListItems.Find(id);
            if (wishListItem == null)
            {
                return HttpNotFound();
            }
            if (!wishListItem.Account.IsOwner(User.Identity.Name))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(wishListItem);
        }

        // POST: WishListItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            WishListItem wishListItem = db.WishListItems.Find(id);
            db.WishListItems.Remove(wishListItem);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult Search(string description, string cost)
        {

            string currentlyLoggedInUser = User.Identity.Name;
            var wishListItems = db.WishListItems
              .Include(w => w.Account)
              .Where(x => x.Account.Owner == currentlyLoggedInUser || x.Account.Recipient == currentlyLoggedInUser);
            if (string.IsNullOrWhiteSpace(description) && string.IsNullOrWhiteSpace(cost))
            {
                return View(wishListItems.ToList());
            }
            else
            {

                if (!string.IsNullOrWhiteSpace(description))
                {
                    wishListItems = wishListItems.Where(x => x.Description.Contains(description));
                }

                if (!string.IsNullOrWhiteSpace(cost) && Regex.IsMatch(cost, @"^\d+([.]\d+)?$"))
                {
                    decimal costDecimal = Decimal.Parse(cost);
                    wishListItems = wishListItems.Where(s => s.Cost == costDecimal);
                }

                return View(wishListItems.ToList());
            }
        }
    }
}

PAN_ParentsBank_Final/Views/WishListItems/Create.cshtml
@model PAN_ParentsBank_Final.Models.WishListItem


<h2>CREATE NEW WISHLIST ITEM</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <label class = "control-label col-md-2">RECIPIENT EMAIL ID</label>
            <div class="col-md-10">
                @Html.DropDownList("AccountId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <h5><strong>ITEM COST</strong></h5>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" , @style="height:40px"} })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <h5><strong>ITEM DESCRIPTION</strong></h5>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", @style = "height:40px" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <h5><strong>ITEM LINK</strong></h5>
            </div>
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control", @style = "height:40px" } })
                @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="control-label col-md-2">
                <h5><strong>PURCHASED</strong></h5>
            </div>
            <div class="col-md-10">
                <div class="checkbox" style="margin-top:10px">
                    @Html.EditorFor(model => model.Purchased)
                    @Html.ValidationMessageFor(model => model.Purchased, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="ADD WISHLIST ITEM" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Index", "WishListItems")';return false;">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> BACK TO LIST
    </button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PAN_ParentsBank_Final/Views/WishListItems/Delete.cshtml
@model PAN_ParentsBank_Final.Models.WishListItem

<h2>DELETE WISHLIST ITEM</h2>

<div>
    <h4>WISHLIST ITEM DETAILS</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
           OWNER EMAIL ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account.Owner)
        </dd>

        <br />

        <dt>
            DATE ADDED
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>
        <br />
        <dt>
            ITEM COST
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <br />
        <dt>
            ITEM DESCRIPTION
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>
        <br />
        <dt>
            ITEM LINK
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>
        <br />
        <dt>
            ITEM PURCHASED ?
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchased)
        </dd>
        <br />
    </dl>

    <h3>Are you sure you want to delete this item?</h3>
    <br />

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="YES, DELETE" class="btn btn-danger" /> |
            <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index", "WishListItems")';return false;">
                <span class="glyphicon glyphicon-circle-arrow-left"></span> NO, BACK TO LIST
            </button>
        </div>
    }
</div>

PAN_ParentsBank_Final/Views/WishListItems/Details.cshtml
@model PAN_ParentsBank_Final.Models.WishListItem


<h2>WISHLIST ITEM DETAILS</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            RECIPIENT EMAIL ID
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Account.Recipient)
        </dd>

        <br />

        <dt>
            DATE ADDED
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <br />

        <dt>
            ITEM COST
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <br />

        <dt>
            ITEM DESCRIPTION
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <br />

        <dt>
            ITEM LINK
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Link)
        </dd>

        <br />  

        <dt>
            ITEM PURCHASED ?
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Purchased)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("EDIT WISHLIST ITEMS", "Edit", new { id = Model.Id , @style="font-size:20pt"}) 
    
    <br />
    <br />

    <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Index", "WishListItems")';return false;">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> BACK TO LIST
    </button>
</p>

PAN_ParentsBank_Final/Views/WishListItems/Edit.cshtml
@model PAN_ParentsBank_Final.Models.WishListItem


<h2>EDIT WISH LIST ITEMS</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            <label class="control-label col-md-2">Recipient</label>
            <div class="col-md-10">
                @Html.DropDownList("AccountId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AccountId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                @Html.HiddenFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Link, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Link, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Link, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Purchased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Purchased)
                    @Html.ValidationMessageFor(model => model.Purchased, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="SAVE ITEM" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Index", "WishListItems")';return false;">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> BACK TO LIST
    </button>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PAN_ParentsBank_Final/Views/WishListItems/Index.cshtml
@model IEnumerable<PAN_ParentsBank_Final.Models.WishListItem>

<script>

    function move() {
        var elem = document.getElementById("myBar");
        var width = 0;
        var remBal = 70 ;
        var max =  remBal;
        var id = setInterval(frame, 0);        
        function frame()
        {
            if (width >= fundsReq)
            {
                clearInterval(id);
            }
            else
            {
                width++;
                elem.style.width = width + '%';
                elem.innerHTML = width * 1 + '%';
            }          

        }

    }
</script>

<h2>WISHLIST ITEMS SUMMARY</h2>

<button type="button" class="btn btn-primary active" onclick="location.href='@Url.Action("create", "WishListItems")';return false;">ADD WISHLIST ITEM</button>

<button type="button" class="btn btn-primary active" onclick="location.href='@Url.Action("search", "WishListItems")';return false;">
    <span class="glyphicon glyphicon-search"></span> SEARCH WISHLIST
</button>

<br />
<br />
<table class="table table-bordered">
    <tr>
        <th>
            RECIPIENT EMAIL ID
        </th>
        <th>
            DATE ADDED
        </th>
        <th>
            ITEM COST
        </th>
        <th>
            ITEM DESCRIPTION
        </th>
        <th>
            ITEM LINK
        </th>
        <th>
            PURCHASED?
        </th>
        <th> CRUD FUNCTIONALITIES</th>
        <th>
            JUMP TO ACCOUNT DETAILS
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Account.Recipient)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateAdded)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Link)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Purchased)
        </td>
        <td>
            @Html.ActionLink("EDIT ITEMS", "Edit", new { id=item.Id }) |
            @Html.ActionLink("ITEM DETAILS", "Details", new { id=item.Id }) |
            @Html.ActionLink("DELETE ITEMS", "Delete", new { id=item.Id })
        </td>
        <td>
            <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Details", "Accounts",new { id = item.Account.Id })';return false;">
                <span class="glyphicon glyphicon-circle-arrow-left"></span> GO!
            </button>
        </td>
    </tr>
}

</table>

@*<button type="button" class="btn btn-info" onclick="move()">CHECK PROGRESS</button>
<br />
<br />*@

<div class="progress" style="height:40px">
    <div class="progress-bar progress-bar-success progress-bar-striped active" id="myBar" role="progressbar" aria-valuemin="0" aria-valuenow="54" aria-valuemax="100" style="width:54%">
        <h4>% OF ITEMS NOT AFFORDABLE</h4>
    </div>
</div>

PAN_ParentsBank_Final/Views/WishListItems/Search.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title></title>
</head>
<body>
    @model IEnumerable<PAN_ParentsBank_Final.Models.WishListItem>

    

    <h2>SEARCH WISHLIST</h2>
    <br />

    @using (Html.BeginForm("Search", "WishlistItems", FormMethod.Get))
    {
        <div class="form-horizontal">
            <div class="form-group">
                @Html.Label("Description", "Description", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.Editor("Description", new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                @Html.Label("Cost", "Price", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.Editor("Cost", new { htmlAttributes = new { @class = "form-control" } })
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="SEARCH" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
    <table class="table table-bordered">
        <tr>
            <th>
               RECIPIENT EMAIL ID
            </th>
            <th>
                DATE ADDED
            </th>
            <th>
                ITEM COST
            </th>
            <th>
                ITEM DESCRIPTION
            </th>
            <th>
                ITEM LINK
            </th>
            <th>
                PURCHASING ITEM?
            </th>
            <th>CRUD FUNCTIONALITY</th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Account.Recipient)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateAdded)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Link)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Purchased)
                </td>
                <td>
                    @Html.ActionLink("EDIT ITEM", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("ITEM DETAILS", "Details", new { id = item.Id }) |
                    @Html.ActionLink("DELETE ITEM", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

    <button type="button" class="btn btn-info" onclick="location.href='@Url.Action("Index", "WishListItems")';return false;">
        <span class="glyphicon glyphicon-circle-arrow-left"></span> BACK TO LIST
    </button>
</body>
</html>